/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDrink: typeof import('./components/AddDrink.vue')['default']
    AddPlayer: typeof import('./components/AddPlayer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DrinkForm: typeof import('./components/DrinkForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PlayerCard: typeof import('./components/PlayerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
